kind: Deployment
apiVersion: apps/v1
metadata:
  name: socket-manager
  labels:
    app: socket-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: socket-manager
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: socket-manager
          env:        
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: socket-manager
                  key: PORT
            - name: INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: socket-manager
                  key: INTERNAL_PORT
            - name: KEY_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: socket-manager
                  key: KEY_PASSPHRASE
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: socket-manager
              mountPath: /app/certs
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/mm-socket-manager:latest
      dnsPolicy: ClusterFirst
      volumes:
        - name: socket-manager
          secret:
            secretName: socket-manager
            # items:
            items:
              - key: clientCA.crt
                path: clientCA.crt
              - key: server.key
                path: server.key
              - key: server.crt
                path: server.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600