apiVersion: v1
kind: Service
metadata:
  name: dc-socket-manager
  labels:
    app: dc-socket-manager
spec:
  selector:
    app: dc-socket-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: 8081-tcp